// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHB97jIcnDyp7JEoFXVJL9oGyhF_R7Z5s',
    appId: '1:664001877901:web:125a77edc9059ff8c44fc4',
    messagingSenderId: '664001877901',
    projectId: 'i-sea-26f32',
    authDomain: 'i-sea-26f32.firebaseapp.com',
    storageBucket: 'i-sea-26f32.appspot.com',
    measurementId: 'G-4SH085RSJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2XAWEtOSA7FwvXrwjkMgGQYBf-WKV5k',
    appId: '1:664001877901:android:bf7ef2465c4dda6bc44fc4',
    messagingSenderId: '664001877901',
    projectId: 'i-sea-26f32',
    storageBucket: 'i-sea-26f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGq_ngT1DeM9ObkOFkn-i9Ri3oTaZMwU',
    appId: '1:664001877901:ios:1ba45f18fabe748ec44fc4',
    messagingSenderId: '664001877901',
    projectId: 'i-sea-26f32',
    storageBucket: 'i-sea-26f32.appspot.com',
    iosBundleId: 'com.example.iSeaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkGq_ngT1DeM9ObkOFkn-i9Ri3oTaZMwU',
    appId: '1:664001877901:ios:02c101cffcfbe1e0c44fc4',
    messagingSenderId: '664001877901',
    projectId: 'i-sea-26f32',
    storageBucket: 'i-sea-26f32.appspot.com',
    iosBundleId: 'com.example.iSeaApp.RunnerTests',
  );
}
